### ISSUE TITLE
Unable to capture MUSHROOM_COW

### ISSUE THREAD

**Issue by ghost** [MagicTeaMC/CatchBall#37]
*Version Information:
```
Server Version: Paper 1.20.6-134-master@4f13be9
Plugin Version: CatchBall 1.2.3
```

*Error Reproduction:
```
Take CatchBall and throw MUSHROOM_COW.
It will reduce the CatchBall but will not drop MUSHROOM_COW heads.
```

*Error Log:
```
[13:09:01 ERROR]: Could not pass event ProjectileHitEvent to CatchBall v1.2.2
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "src" is null
        at java.base/java.util.Base64$Decoder.decode(Base64.java:593) ~[?:?]
        at org.bukkit.craftbukkit.profile.CraftProfileProperty.decodeBase64(CraftProfileProperty.java:63) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.profile.CraftProfileProperty.decodePropertyValue(CraftProfileProperty.java:71) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.profile.CraftPlayerTextures.ensureLoaded(CraftPlayerTextures.java:99) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.profile.CraftPlayerTextures.isEmpty(CraftPlayerTextures.java:163) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:139) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:708) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:63) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.CraftWorld.dropItem(CraftWorld.java:746) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.CraftWorld.dropItem(CraftWorld.java:738) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at CatchBall-1.2.3.jar/com.github.nutt1101.event.HitEvent.CatchBallHitEvent(HitEvent.java:164) ~[CatchBall-1.2.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor791.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-134-4f13be9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1497) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:202) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:69) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1415) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1301) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:922) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:902) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by MagicTeaMC** [comment]
Could you try to edit `plugins/CatchBall/entity.yml`
```yml
    MUSHROOM_COW:
        DisplayName: "MUSHROOM_COW"
        Skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmI1Mjg0MWYyZmQ1ODllMGJjODRjYmFiZjllMWMyN2NiNzBjYWM5OGY4ZDZiM2RkMDY1ZTU1YTRkY2I3MGQ3NyJ9fX0="
```
to
```yml
    MUSHROOM_COW:
        DisplayName: "MUSHROOM_COW"
        Skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDBiYzYxYjk3NTdhN2I4M2UwM2NkMjUwN2EyMTU3OTEzYzJjZjAxNmU3YzA5NmE0ZDZjZjFmZTFiOGRiIn19fQ=="
```
I think this is cause by it, but I'm not sure if this is a problem

**Comment by ghost** [comment]
*Version Information:
```
Server Version: Paper 1.20.6-134-master@4f13be9
Plugin Version: CatchBall 1.2.3
```

*Error Reproduction:
```
After updating plugins/CatchBall/entity.yml, the error persists even after reloading the plugin or restarting the server.
```

*Error Log
```
[09:56:09 ERROR]: Could not pass event ProjectileHitEvent to CatchBall v1.2.2
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "src" is null
        at java.base/java.util.Base64$Decoder.decode(Base64.java:593) ~[?:?]
        at org.bukkit.craftbukkit.profile.CraftProfileProperty.decodeBase64(CraftProfileProperty.java:63) ~[paper-1.20.6.jar:1.20.6-134-4f13
be9]
        at org.bukkit.craftbukkit.profile.CraftProfileProperty.decodePropertyValue(CraftProfileProperty.java:71) ~[paper-1.20.6.jar:1.20.6-1
34-4f13be9]
        at org.bukkit.craftbukkit.profile.CraftPlayerTextures.ensureLoaded(CraftPlayerTextures.java:99) ~[paper-1.20.6.jar:1.20.6-134-4f13be
9]
        at org.bukkit.craftbukkit.profile.CraftPlayerTextures.isEmpty(CraftPlayerTextures.java:163) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:139) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:708) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:63) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.CraftWorld.dropItem(CraftWorld.java:746) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at org.bukkit.craftbukkit.CraftWorld.dropItem(CraftWorld.java:738) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at CatchBall-1.2.3.jar/com.github.nutt1101.event.HitEvent.CatchBallHitEvent(HitEvent.java:164) ~[CatchBall-1.2.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor901.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-134-4f13be9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-134-4
f13be9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1497) ~[paper-1.20.6.jar:1.20.6-134-
4f13be9]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:202) ~[paper-1.20.6.jar:1.20.6-134-4f1
3be9]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:69) ~[paper-1.20.6.jar:1.20.6-134-4f13be9
]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1415) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1301) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:922) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:902) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by MagicTeaMC** [comment]
This is the solution, but I think it won't update itself, so I post it here
```yml
    MOOSHROOM:
        DisplayName: "MOOSHROOM"
        Skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDBiYzYxYjk3NTdhN2I4M2UwM2NkMjUwN2EyMTU3OTEzYzJjZjAxNmU3YzA5NmE0ZDZjZjFmZTFiOGRiIn19fQ=="
```
